name: Canary Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *' # Everyday 16:00 UTC

permissions: {}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  canary-test:
    strategy:
      matrix:
        include:
          - os: macos-latest
            xcode-version: 14.3.1
            device: iPhone 14 Pro
            version: 16.4
    name: Canary Test - Xcode ${{ matrix.xcode-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 #v4.1.1
        with:
          persist-credentials: false



      - name: Setup Ruby
        uses: ruby/setup-ruby@22fdc77bf4148f810455b226c90fb81b5cbc00a7 # v1.171.0
        with:
          ruby-version: '3.3.1'
          bundler-cache: true
          working-directory: ${{ github.workspace }}/canaries/example

      - name: Set Default Xcode Version to ${{ matrix.xcode-version }}
        run: |
          sudo xcode-select -s "/Applications/Xcode_${{ matrix.xcode-version }}.app"
          xcodebuild -version

      - name: Run Tests - ${{ matrix.device }} with iOS ${{ matrix.version }}
        working-directory: ${{ github.workspace }}/canaries/example
        run: bundle exec fastlane scan --device "${{ matrix.device }}" --deployment_target_version "${{ matrix.version }}"

